/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dmtavt.tests.woodstox;

import org.junit.jupiter.api.Test;

import javax.xml.stream.XMLStreamException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import static com.dmtavt.tests.woodstox.App.fileSizeHumanReadable;

class WoodstoxParserTests {
    static final int numEntries = 4000000;
    static final Path dir = Paths.get("C:\\tmp\\xml");

    static Path getFilePath() {
        return dir.resolve("xml-" + numEntries + ".xml");
    }

    @Test void TestFileGeneration() throws IOException {
        FakeData.createHugeXml(getFilePath(), numEntries);
        long fileSize = Files.size(getFilePath());
        System.out.printf("Created file (%s) at: %s", fileSizeHumanReadable(fileSize), getFilePath());
    }

    @Test void TestFileRead() throws IOException, XMLStreamException {
        long timeLo = System.nanoTime();
        List<WoodstoxParser.Person> people = WoodstoxParser.parse(getFilePath());
        long timeHi = System.nanoTime();

        long totalSalary = people.stream().mapToLong(p -> p.salaryAmount).sum();
        double seconds = (timeHi - timeLo) / 1e9f;
        long fileSize = Files.size(getFilePath());
        String fs = fileSizeHumanReadable(fileSize);
        System.out.printf("Parsed %d persons (%s) in %.2f seconds, total salary %.0E\n", people.size(), fs, seconds, (double)totalSalary);
    }
}
