/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dmtavt.tests.woodstox;

import com.dmtavt.tests.BaseParserTests;
import com.dmtavt.tests.Person;
import org.junit.jupiter.api.Test;

import javax.xml.stream.XMLStreamException;
import java.io.IOException;
import java.nio.file.Files;
import java.util.List;

import static com.dmtavt.tests.App.fileSizeHumanReadable;

class WoodstoxParserTests extends BaseParserTests {

    @Test void TestFileRead() throws IOException, XMLStreamException {
        long timeLo = System.nanoTime();
        List<? extends Person> people = WoodstoxParser.parse(getFilePath());
        long timeHi = System.nanoTime();

        long totalSalary = people.stream().mapToLong(p -> p.salaryAmount).sum();
        double seconds = (timeHi - timeLo) / 1e9f;
        long fileSize = Files.size(getFilePath());
        String fs = fileSizeHumanReadable(fileSize);
        System.out.printf("Parsed %d persons (%s) in %.2f seconds, total salary %.0E\n", people.size(), fs, seconds, (double)totalSalary);
    }
}
